### ISSUE TITLE
Alwayse launch CodeServer in run mode

### ISSUE THREAD

**Issue by foal** [gwt-plugins/gwt-eclipse-plugin#101]
It isn't necessary to lunch CodeServer in debug mode IMHO.

**Comment by axls** [comment]
I think, debugging of deferred binding generators will be broken in this case.

**Comment by foal** [comment]
Hmm.. Never used it, but It may be a reason to keep it in debug mode.

**Comment by branflake2267** [comment]
There are any flag differences from debug or run mode. Are you saying something is broken running on the the code server in one of the modes?

**Comment by branflake2267** [comment]
There is no difference in arguments provided to the jar, so I'm going to close this. Unless it can be proven otherwise.
