### ISSUE TITLE
Add index.html to repos. 

### ISSUE THREAD

**Issue by priand** [gwt-plugins/gwt-eclipse-plugin#106]
Here is what is displayed when you click on the link from the home page:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by branflake2267** [comment]
Gotcha. That's because I don't have an index mapped on Google storage. The files are there for the update site.

**Comment by branflake2267** [comment]
TODO: map an index page to update site end point.
