### ISSUE TITLE
Deploying Managed VM Appengine Project w/Dockerfile Fails

### ISSUE THREAD

**Issue by unitydynamics** [gwt-plugins/gwt-eclipse-plugin#108]
Steps to recreate:

Step 1) Create a minimal Appengine project in Eclipse (Luna Service Release 2 (4.4.2), Google Plugin Version: 3.8.0.v201410302155-rel-r44)

Step 2) Change appengine-web.xml to include your valid app ID and deploy through Eclipse plugin!  Success.  

Step 3) Add &lt;vm&gt;true&lt;/vm&gt; to appengine-web.xml and deploy through Eclipse plugin!  Success.  You can even see your new GAE-generated instance through the console.  

Step 4) Create a "Dockerfile" and put it in the same directory as WEB-INF (not inside WEB-INF). To start I'm trying the most basic Dockerfile specifications:

FROM gcr.io/google_appengine/java-compat
ADD . /app

This is essentially the same as the system-generated Dockerfile you'll see when you SSH into the instance after Step 3.

Unfortunately in all of my trials I'm confronted with the same generic error (which doesn't help me debug the problem). This is the console log in Eclipse:

------------ Deploying frontend ------------

Preparing to deploy:
Created staging directory at: 'C:\Users\Robert\AppData\Local\Temp\appcfg218911648519609150.tmp'
Scanning for jsp files.
Scanning files on local disk.
Initiating update.
Cloning 2 static files.
Cloning 73 application files.

Deploying:
Uploading 0 files.
Deploying new version.

Verifying availability:
Will check again in 1 seconds.
Will check again in 2 seconds.
Will check again in 4 seconds.
Will check again in 8 seconds.
Will check again in 16 seconds.
Giving up due to transient errors. Please try again. Version: driver-engine:2.389314165949012006
Rolling back the update.
java.lang.RuntimeException: Fatal problem encountered during deployment. Please refer to the logs for more information.

Debugging information may be found in C:\Users\Robert\AppData\Local\Temp\appengine-deploy6234059854793118824.log

-----------------------------------------------------
The specified log file contains:

Unable to update:
java.lang.RuntimeException: Fatal problem encountered during deployment. Please refer to the logs for more information.
at com.google.appengine.tools.admin.AppVersionUpload.isServing(AppVersionUpload.java:1096)
at com.google.appengine.tools.admin.AppVersionUpload.access$200(AppVersionUpload.java:46)
at com.google.appengine.tools.admin.AppVersionUpload$2.call(AppVersionUpload.java:929)
at com.google.appengine.tools.admin.AppVersionUpload$2.call(AppVersionUpload.java:926)
at com.google.appengine.tools.admin.AppVersionUpload$3.call(AppVersionUpload.java:1233)
at com.google.appengine.tools.admin.AppVersionUpload$3.call(AppVersionUpload.java:1230)
at com.google.appengine.tools.admin.AppVersionUpload.retryWithBackoffOptional(AppVersionUpload.java:1270)
at com.google.appengine.tools.admin.AppVersionUpload.retryWithBackoff(AppVersionUpload.java:1228)
at com.google.appengine.tools.admin.AppVersionUpload.commit(AppVersionUpload.java:926)
at com.google.appengine.tools.admin.AppVersionUpload.uploadFilesTransaction(AppVersionUpload.java:228)
at com.google.appengine.tools.admin.AppVersionUpload.doUpload(AppVersionUpload.java:200)
at com.google.appengine.tools.admin.AppAdminImpl.doUpdate(AppAdminImpl.java:571)
at com.google.appengine.tools.admin.AppAdminImpl.update(AppAdminImpl.java:58)
at com.google.appengine.eclipse.core.proxy.AppEngineBridgeImpl.deploy(AppEngineBridgeImpl.java:433)
at com.google.appengine.eclipse.core.deploy.DeployProjectJob.runInWorkspace(DeployProjectJob.java:158)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

So what's happening here?  Why doesn't my Dockerfile simply get uploaded.  I've got a bounty on this issue.  Help greatly appreciated.
-Robert

**Comment by branflake2267** [comment]
The first thing that comes to mind is how big is the file? Can you do a screenshot of the webapp/war directory that you want uploaded? There is a size limit to how big the files get uploaded to the static web app directory on app engine. I suspect it's going over that size. If not there may be a timeout occurring. What I've done for large size files is use a servlet to intercept the request and proxy it to google storage.

**Comment by unitydynamics** [comment]
Thanks Brandon for the reply.  The entire war is simply one "hello world" servlet.  The only difference between success (step 3) and failure (step 4) is a single Dockerfile file with only a few bytes of data in it!

**Comment by unitydynamics** [comment]
If we look at the isServing() method at the source point of failure... it looks like we could have had more detail if "result" was included in the error.  Unfortunately it's not so I'm not sure I will ever know why this deployment fails.  https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/tools/admin/AppVersionUpload.java?r=530

**Comment by branflake2267** [comment]
Gotcha. I might suggest adding a pom.xml with the official app engine plugin. Configure the app engine plugin and run it's deploy. I've found it to be more tolerable at times to uploading. I've got some configs around if you need something. Otherwise I'd need a test case to see what is going on. I can't check it right away if you do send one, but can schedule it.

**Comment by unitydynamics** [comment]
Maybe I'm oldschool.  If you have advice or direction on setting up Eclipse to work with Maven goals, etc please point me to them.  I'll tinker on my own and post my minimal project if I can't figure it out.  Thanks again.

**Comment by branflake2267** [comment]
https://gwt.googlesource.com/gwt/+/master/samples/mobilewebapp/pom.xml - has the config

https://cloud.google.com/appengine/docs/java/tools/maven - docs on it

**Comment by unitydynamics** [comment]
Well I love the original non-maven plugin. Tonight I've been fussing with Maven, gcloud, Eclipse/Maven integration... it's a mess.  A big mess.  I loved it when my world was simple.  When the Google Plugin for Eclipse was all I needed.  Right click on project > Google > Deploy to App Engine.  Are you telling me those days are gone?  Sigh.

**Comment by unitydynamics** [comment]
[MinimalTest.zip](https://github.com/gwt-plugins/gwt-eclipse-plugin/files/66213/MinimalTest.zip)

Ok here is my minimal Eclipse project.  It's started from the standard project built via the "New Web Application Project..." option in the Google Plugin for Eclipse.

To run it you'll need to put your own app-id in appengine-web.xml.  And if you haven't deployed a "default" module previously you'll have to jump through that hurdle or remove my module specification.

As packed this is on my "Step 4" described above.  Fails to deploy when using Google > Deploy to App Engine.  Simply delete the Dockerfile... and wow it works!  Problem is I want to deploy my own Dockerfile.  

I hope someone can make my Christmas better.  I don't want a solution that involves switching my entire workflow to use Maven or some other command-line mess.

**Comment by unitydynamics** [comment]
Just FYI to anyone who happens upon this.  I found a workaround by using gcloud to deploy.  I did open an official ticket with Google so hopefully this is on their radar.

**Comment by branflake2267** [comment]
Thanks for the details and feedback on gcloud.

**Comment by branflake2267** [comment]
This will be shifting to the Google Cloud tools plugin.
