### ISSUE TITLE
@Source referenced as @ClientBundle.Source not recognized by ClientBundleValidator

### ISSUE THREAD

**Issue by lleevvyy** [gwt-plugins/gwt-eclipse-plugin#123]
Hi, the code below will raise an error of ClientBundle validator:

class ClientBundleImpl implements ClientBundle {

  @ClientBundle.Source("file.gss")
   public CssImpl css ();
}

The error will say, that gss file "css" is missing. It is because, annotation @Source is not recognized by the GWT Plugin. Plugin's class ClientBundleValidator, method isSourceAnnotation doesn't cover the case, when @Source is referenced as @ClientBundle.Source. GWT compiles without problems when that kind of reference is used. 

Fix will be appreciated. Thanks.

**Comment by branflake2267** [comment]
Thanks for reporting. GSS fixes are on the agenda in the near future.

**Comment by branflake2267** [comment]
This is a code construction issue.

This is how it could be constructed.
```
import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.CssResource;

interface ClientBundleImpl extends ClientBundle {

  interface CssImpl extends CssResource {
    String flexAll();

    String flexOff();

    String flex();

    String toolButton();

    String toolButtonOver();

    String textFieldButton();
  }

  @Source("styles.gss")
  CssImpl css();

}
```
