### ISSUE TITLE
com.google.gdt.eclipse.maven.googleProjectConfigurator error

### ISSUE THREAD

**Issue by bbrudnoy** [gwt-plugins/gwt-eclipse-plugin#126]
Appeared a couple of snapshot upgrades ago. The full text of the error is:
```
'Project configurator "com.google.gdt.eclipse.maven.googleProjectConfigurator" required by plugin
execution "org.apache.maven.plugins:maven-war-plugin:2.2:war (execution: default-war, phase:
package)" is not available. To enable full functionality, install the project configurator and run Maven-
>Update Project Configuration.'
```
![screen shot 2015-12-30 at 9 03 09 am](https://cloud.githubusercontent.com/assets/5347698/12051656/8a640bd2-aed4-11e5-8143-2dd59ed3691b.png)

Eclipse Mars 4.5.1, Google Plugin for Eclipse 4.4 (0.0.0.201512280757)

**Comment by branflake2267** [comment]
Is this still occurring? I haven't seen this issue occur.

**Comment by branflake2267** [comment]
Closing unsure how to reproduce.
