### ISSUE TITLE
When @Source contains characters not allowed in java package name, plugin throws an error

### ISSUE THREAD

**Issue by lleevvyy** [gwt-plugins/gwt-eclipse-plugin#132]
Hi, GWT allows to define @Source file, whose path or name contains any kind of characters, however Eclipse plugin throws an error if for example "-" is used. Example:
@Source("resources/folder-name/file-name.js") 
Above will be accepted by GWT complier, but plugin will throw an error.

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/348
