### ISSUE TITLE
Support Eclipse Neon June

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#139]
Start testing on Eclipse Neon.

**Comment by TDesjardins** [comment]
The release of Neon is near. Is there any news on gwt-eclipse-plugin support?

**Comment by wbabachan** [comment]
Not working in Eclipse with Gradle. I get error: 

java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class

And I exclude asm from my projects, specially GIN and Guice...
