### ISSUE TITLE
 Restart Codeserver & Web Server sync and not sync

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [gwt-plugins/gwt-eclipse-plugin#140]
Sometimes the Code Server gets out of wack, can't find a file for some reason and generally needs to be restarted.  Currently the "restart web server" button only restarts the Jetty server for the actual web application and to restart the Code Server, you need to restart the whole dev mode setup when using the plugin.  It would be a nice enhancement, if in the Development tab, we added a "Restart Code Sever" button that just killed and relaunched the Code Server thread.

**Comment by branflake2267** [comment]
There is a setting for disconnecting the restarting of both services. I'm getting the feeling b/c more than one person has submitted the bug, so it needs to be more visible. 

It can be disconnected in the GWT > GWT facet settings. 
![screen shot 2016-08-09 at 5 04 04 pm](https://cloud.githubusercontent.com/assets/1326504/17537653/605cd5b0-5e53-11e6-86ad-60e295c385a8.png)

**Comment by branflake2267** [comment]
Goal: make it easier to disconnect the two servers. Or add menu item to only restart one or the other.
