### ISSUE TITLE
"Development Mode" page - double click is not working anymore.

### ISSUE THREAD

**Issue by slavap** [gwt-plugins/gwt-eclipse-plugin#151]
Eclipse 4.5.2, after updating plugin double click has stopped working, though right click -> Open is working just fine.

**Comment by branflake2267** [comment]
I've notice this too, and been annoyed by this too.

**Comment by branflake2267** [comment]
I found the issue. I was greedy when I removed the speed tracer, and removed a line that I shouldn't have.

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/155

**Comment by branflake2267** [comment]
I'll push up the new bits to the snapshot soon.

**Comment by slavap** [comment]
Thanks, it's working again.

**Comment by branflake2267** [comment]
You're welcome. Good to hear. Thanks for the update.
