### ISSUE TITLE
When opening the launch configuration Eclipse prompts for an error com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup cannot be found by com.google.gwt.eclipse.core_0.0.0.201608101418

### ISSUE THREAD

**Issue by samgabriel** [gwt-plugins/gwt-eclipse-plugin#168]
Looks like the plugin.xml is not updated to reflect the new package of the GWTJunitTabGroup https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/1ef5a70bf6a1dabbdb6fd327a4750c1468e0227d/plugins/com.google.gwt.eclipse.core/plugin.xml
has 
`<launchConfigurationTabGroup
            **class="com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup"**
            helpContextId="org.eclipse.jdt.junit.junit_tab_group"
            id="com.google.gwt.eclipse.core.launch.gwtJUnitTabGroup"
            type="com.google.gwt.eclipse.core.launch.gwtJUnit">
         <launchMode
               description="Debug a GWT JUnit Test"
               mode="debug"
               perspective="org.eclipse.debug.ui.DebugPerspective">
         </launchMode>
         <launchMode
               description="Run a GWT JUnit Test"
               mode="run">
         </launchMode>
      </launchConfigurationTabGroup>
`

But the actual class is here com.google.gwt.eclipse.core.launch.ui.tab_groups.GWTJunitTabGroup
https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/1ef5a70bf6a1dabbdb6fd327a4750c1468e0227d/plugins/com.google.gwt.eclipse.core/src/com/google/gwt/eclipse/core/launch/ui/tab_groups/GWTJUnitTabGroup.java

**Comment by branflake2267** [comment]
Thanks for reporting! Feel free to submit a patch, and let me know how you test it. Or I'll schedule it  in the next batch of bug fixes. If you want to pull a request you could even edit it in github and pull it and let me know how you test it. It will be a couple weeks before another batch comes out from me.  Thanks, Brandon

**Comment by aino-vedang** [comment]
Is this bug fixed in latest yet? Because I am still facing this issue.

**Comment by branflake2267** [comment]
Sorry I haven't had time to get to this yet. I'll see if I can get some time next week to work on Eclipse.

**Comment by zmichal-anasoft** [comment]
I found this issue again in the latest version of this plugin. The version of GWT core is 2.9.0. The version of eclipse is 2020-09. 

```
Plug-in com.gwtplugins.gwt.eclipse.core was unable to load class com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup.
com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup cannot be found by com.gwtplugins.gwt.eclipse.core_3.0.0.201710131939
```

Thanks+m

**Comment by thudarm** [comment]
I am experiencing this issue, getting the following error when attempting to edit or create a GWT Unit Test Run Configuration: 
Plug-in com.gwtplugins.gwt.eclipse.core was unable to load class com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup.
com.google.gwt.eclipse.core.launch.ui.groups.GWTJUnitTabGroup cannot be found by com.gwtplugins.gwt.eclipse.core_3.0.0.201710131939

I am using the latest GWT Plugin:
  GWT Eclipse Plugin	3.0.0.201710131939	com.gwtplugins.eclipse.suite.v3.feature.feature.group	GWT Eclipse Plugin
Eclipse: Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2021-03 (4.19.0)
Build id: 20210312-0638
Was there just a bug fix that is suppose to be in this version, or is there some kind of setting I can change?

**Comment by eliasbalasis** [comment]
Same issue here, with same plugin version
Eclipse 2021-03 (4.19.0)
GWT Eclipse Plugin 3.0.0.201710131939
