### ISSUE TITLE
uibinder namespace issue

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#285]
https://plus.google.com/u/0/+BrandonDonnelson/posts/cLc2dJ6f45U - origination in comments

I face a problem declaring a namespace which points to a class instead of a package. I think I can do this in previous plugin:

<ui:UiBinder xmlns:ui="..." xmlns:my="my.app.client.MyClass"> 
   ...
   my:AppDialog../my:AppDialog
/ui:UiBinder
- https://github.com/andirady/forbrandon - testcase

**Comment by andirady** [comment]
I made changes to the code, but I don't know how to test the plugin. Here's the patch http://pastebin.com/e75WbFG5

**Comment by branflake2267** [comment]
fixed in https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/347. I added something less greedy. Thanks for the patch!
