### ISSUE TITLE
JSNI code is not recognized

### ISSUE THREAD

**Issue by rkfg** [gwt-plugins/gwt-eclipse-plugin#324]
This has been bugging me for a while now. It worked on Eclipse 3.x but probably was broken on 4.x or some time later. This is how JSNI code looks for me on Eclipse Mars 2 (4.5.2), GWT Eclipse Plugin 3.0.0.201611042254:
![2016-12-10_14-40-07](https://cloud.githubusercontent.com/assets/184066/21073072/af853756-bee6-11e6-80a7-cd598d1b43b0.png)

Of course, I'm using "GWT Java Editor" (Open with ⇒ GWT Java Editor) but it looks exactly the same as with the regular Java Editor. Completion also doesn't work and it's essential with JSNI as I sometimes need to call Java methods and deducing and writing signatures by hand is a pain. Same issue with the official Google Plugin release. As I said, it's broken for me for quite a while. Same results on two machines, at work and at home. I'm using Debian testing, OpenJDK 1.8.0_111-8u111-b14-3-b14 (as per java -version).

**Comment by rkfg** [comment]
Err... for some mystical reason it suddenly started working after I restarted Eclipse. Weird, as I already did that after installing the plugin. Closing for now, will reopen if/when I have any additional details.

**Comment by branflake2267** [comment]
Thanks for the update.

**Comment by rkfg** [comment]
For those who may come here looking for a solution to the same problem, Google's plugin from https://dl.google.com/eclipse/plugin/4.5 *indeed* has this problem. I installed it back and yes, it doesn't parse JSNI at all though it certainly did in some older Eclipse (Juno and maybe Kepler). However, this particular beta works fine, note that after installing it over the Google's build it required me to open the file in GWT Java Editor twice for it to start working. Only needed to do it once right after installing then it's all right.

**Comment by rkfg** [comment]
Ok, solved this one. The problem was that all my projects were created from Maven archetypes and then imported to Eclipse. This option (Use GWT) in project settings wasn't enabled:
![2016-12-12_09-46-21](https://cloud.githubusercontent.com/assets/184066/21090346/293430c4-c050-11e6-8b55-9c7b28887cb4.png)

After enabling it a message box appears that explicitly states that JSNI will be supported from now on. And it works in Google's release as well as in this beta.

**Comment by branflake2267** [comment]
That dialog shows up when the GWT Nature is added to the project. It asks to re-open the files with the GWT editor, which is enhanced Java editor, meaning it has JSNI stuff and such. That's a good sign the project configurator added the GWT nature. This is a normal process if the files were opened before the GWT nature was applied.
