### ISSUE TITLE
DevMode without embedded server

### ISSUE THREAD

**Issue by totoheros** [gwt-plugins/gwt-eclipse-plugin#335]
I am using an non jee server (WebObjects from Apple). In google Plugin, I have a separate launch config for the GWT part. The argument is : -noserver -startupUrl http://localhost:port/MyServerApp....
This works perfectly.

I try to use the gwt-plugin but in the GWT config, I cannot use my Url.
If I add -startupUrl  in arguments and  uncheck built-in server, I cannot save that config.

Why that ? Should I do it an other way ?

Thanks in advance for any help
Pierre

**Comment by paxdei** [comment]
I got the same problem.

The issue is in  com.google.gdt.eclipse.suite.launch.ui.tabs.WebAppServerTab.isValid(ILaunchConfiguration)

```
    // TODO ?
    if (runServerButton != null) {
      if (!runServerButton.getSelection()) {
        setErrorMessage("App Engine projects need to run the built-in server.");
        return false;
      }
    }
```

There used to be an additional check for WebAppLaunchUtil.projectIsGaeOnly(project) in the if clause.

IMO this entire section must be removed, it just renders the runServerButton useless.

Please fix this, it's actually the last thing holding us back from rolling out gwt 2.8.0

Thanks!

**Comment by branflake2267** [comment]
Thanks for reporting. The CodeServer Launcher can be used in the mean time to launch (super) dev mode and debug on any server. It's better to use when debugging with web servers. Use the the -launcherDir /path/to/war/dir and you'd be set. Are you trying to use classic dev mode?

**Comment by paxdei** [comment]
Yes, it's just for the classic devmode. I know it is deprecated and everybody should use the sdm, but I'm just so much more productive with it. (Breakpoint -> modify code -> save -> hot code swap, all without needing to reload the page, at least in presenter classes)

**Comment by branflake2267** [comment]
Gotcha, good to know for testing.

**Comment by branflake2267** [comment]
I'm not able to replicate the issue. 

If I have a configuration like this pointing to a basic web server `python -m SimpleHTTPServer 8080`,  it works. 
```
-nosuperDevMode -war /Users/branflake2267/Downloads/tmp -remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -startupUrl MyGxtProject40.html -logLevel INFO -bindAddress 0.0.0.0 -codeServerPort 9997 -noserver -startupUrl http://192.168.1.16:8080/ com.sencha.gxt.test.MyGxtProject40
```

**Comment by branflake2267** [comment]
I forgot to mention the arguments are persisting. If you see some other behavior, I need the steps to reproduce it. Or better yet, provide a video of the issue.

**Comment by paxdei** [comment]
Hi Brandon,

the issue is in the launch config UI. Here is a screen cap that illustrates it

![issue 335 explained](https://cloud.githubusercontent.com/assets/15179710/23496328/dc550690-ff1d-11e6-8b6f-923fc9ae583d.png)

**Comment by branflake2267** [comment]
ah, thanks for the details, I'll see what I can do about that.

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/349 - now I remember why I put that todo. :) Good cal.. Thanks.
