### ISSUE TITLE
AnalyticsPingManager assumes that product is not null

### ISSUE THREAD

**Issue by dfht** [gwt-plugins/gwt-eclipse-plugin#336]
It's legitimate to run an Eclipse application without specifying a product. However in the AnalyticsPingManager, on line 101 (in code I have at least), I get a null pointer as it assumes that there is a product.

  setCustomDimension(
        parametersMap, CustomDimensionName.ECLIPSE_PRODUCT_ID, Platform.getProduct().getId());

**Comment by dfht** [comment]
There's another on line 134 of the 'UpdateSiteURLGenerator'
`updateQueryBuilder.setProductId(Platform.getProduct().getId());`

**Comment by dfht** [comment]
Apologies if fixed in later code bases than I have loaded!

**Comment by dfht** [comment]
Actually, I only get this error when running from my plug-ins workspace, so 'something' deduces a product when  i build out and run from there. That being so, you can close this if you want (although i guess a null check wouldn't hurt ). In other words, If I stick a -product argument in my Eclipse application launcher all is well, although for everything else I run it's never needed....
Normally, when running an Eclipse application from Eclipse, your choice of whether you are running a 'product' or 'application' is mutually exclusive (via radio buttons), which is what makes me think a null product is intended to be legitimate.

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/342
