### ISSUE TITLE
GWT plug-ins check for updates and do analytics ping whenever a Java build occurs (on a GWT Project)

### ISSUE THREAD

**Issue by dfht** [gwt-plugins/gwt-eclipse-plugin#337]
I do not think it is sensible for the GWT plug-ins to check for GWT plug-in updates on every java compile of any project with a GWT nature. This can be detrimental to performance. 
I know that update checking can be turned off in the preferences, but perhaps just checking on Eclipse start-up or something (or once a day or whatever)  would be more sensible (just a thought)?

Much more annoying than the updates is the compilation analytics ping request as there doesn't seem to be a way of turning this off, and (again) it happens on every Java build of a GWT natured project!

It should at least respect the general error reporting preferences (e.g.org.eclipse.epp.logging.aeri.ide/sendMode=NEVER) and enable me to opt out of sending information back etc. Also, it does of course fill up my logs with (what to me at least is) not useful information (although it is not alone in that of course).

`/**
 * A compilation participant that is used to trigger an update check of the GWT Plugin's feature
 * whenever a Java build is triggered on a GWT project.
 */
public class UpdateTriggerCompilationParticipant extends CompilationParticipant {

  @Override
  public boolean isActive(IJavaProject project) {
    if (!project.exists()) {
      return false;
    }

    if (GWTNature.isGWTProject(project.getProject())) {
      GdtExtPlugin.getFeatureUpdateManager().checkForUpdates();
      GdtExtPlugin.getAnalyticsPingManager().sendCompilationPing();
      return true;
    } else {
      return false;
    }
  }
}
`

**Comment by branflake2267** [comment]
I've got the first fix in for this built and deployed to staging. The next fix will come as soon as I get time. I'm going to add a preference to turn it off. Good point.

**Comment by branflake2267** [comment]
This is fixed although not releated yet.
