### ISSUE TITLE
@Source annotation validation in V3 ignores the fact that DefaultExtensions has @Inherited

### ISSUE THREAD

**Issue by skarzhevskyy** [gwt-plugins/gwt-eclipse-plugin#339]
After upgrade to V3 version of plugin (3.0.0.201611042254) from previews version (0.0.0.201609232204) the new validation errors started to appear:

> Method requires an @Source annotation (com.google.gwt.resources.client.ImageResource does not define any default extensions)

The code example that produce this:

```
public interface MyImages extends ClientBundleWithLookup {
      ImageResource clear();
}
```

The workaround is to Disable ClientBundle "Method required  @Source"  in options.

Maybe related to #123

**Comment by branflake2267** [comment]
I've noticed this too and I'm scheduling this in my fixes next week.

**Comment by branflake2267** [comment]
Fix is in PR.

**Comment by skarzhevskyy** [comment]
@branflake2267 ,  This problem still present in latest version GWT Eclipse Plugin	3.0.0.201703272136

**Comment by branflake2267** [comment]
I suspect this might be because the setting was persisted into the .settings for the plugin. If you wipe out settings and try again would it work?

**Comment by skarzhevskyy** [comment]
removed:
```
.settings\com.google.gdt.eclipse.core.prefs
.settings\com.gwtplugins.gwt.eclipse.core.prefs
```
 _errors not changed._

---
Also fresh new Eclipse  eclipse-committers-neon-3-win32-x86_64,  Plus new Workplace. -> _the same problem._

---
BTW the new install/Workplace have this validation 'Ignore' by default. 
GWT -> Errors/Warnings -> GWT  ClientBundle  - > Method required @Source annotation -> Ignore.
