### ISSUE TITLE
Remove all .project, .classpath and .settings files from project git indexing. 

### ISSUE THREAD

**Issue by dfht** [gwt-plugins/gwt-eclipse-plugin#345]
In the Git repository after I clone, I see that com.gwtplugins.gwt.eclipse.gss doen't have Eclipse .project file, and so I have to add one manually so I can import it into my workspace.

**Comment by dfht** [comment]
Also no .classpath file. Whilst I understand they are probably deduced from the pom, the lack of then causes problems during initial loading into Eclipse......

**Comment by branflake2267** [comment]
I need to remove all of the .project, .classpath and /.settings files. The are created on import. Import the project as an existing maven project.

**Comment by dfht** [comment]
Thanks -  always import via 'import existing projects' - I didn't notice there was an 'import as existing maven project'. That's good to know as I have many projects where I commit .classpath and .project files when they are in fact either generated from poms or from models, so this could be a handy tip 👍

**Comment by branflake2267** [comment]
Good point, I'll update the readme.
