### ISSUE TITLE
GWT Plugin 3.0.0 is incompatible with existing GWT projects under Eclipse Oxygen

### ISSUE THREAD

**Issue by WTThomas** [gwt-plugins/gwt-eclipse-plugin#366]
Hi!

After update to Eclipse Oxygen I've installed the GWT Plugin 3.0.0 via Eclipse Marketplace.
Now I'm unable to compile my "old" GWT projects I started with the old Google Plugin for Eclipse.

The compile popup says that my project is not a GWT project.
So I tried to re-enable GWT on my project (Right click on the project --> GWT --> Settings).
I receive following message: "The currently displayed page contains invalid values.)
![image](https://user-images.githubusercontent.com/3327272/31495490-190e4cfa-af58-11e7-9950-3b022447e977.png)
After pressing OK it looks broken like this:
![image](https://user-images.githubusercontent.com/3327272/31495561-5eac3b14-af58-11e7-90b4-161dee291e61.png)

On each other project which wasn't a GWT project before the dialogue looks normal and I can choose the right SDK.

Regards
Tom

**Comment by branflake2267** [comment]
I'm going to schedule to work on this tomorrow.

**Comment by branflake2267** [comment]
Fix may be in the works for this. Pushing to staging now.
