### ISSUE TITLE
UIBInder validation of super interface methods

### ISSUE THREAD

**Issue by seamusmac** [gwt-plugins/gwt-eclipse-plugin#373]
If you import the following project into eclipse.
You will see that the ui.xml file contains a validation error when it should not.

https://github.com/seamusmac/gwt-invalid-xml

**Comment by seamusmac** [comment]
I spent a little bit of time trying to figure this out, but it seems to be quite a difficult one given that its related to generics. I don't know JDT too well, and couldn't figure out how to resolve Type 'T'

The line 
https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/master/plugins/com.gwtplugins.gwt.eclipse.core/src/com/google/gwt/eclipse/core/uibinder/UiBinderUtilities.java#L405 returns null for the type T which is why it shows a validation warning in eclipse

@branflake2267  any idea if its possible to resolve the generic type? or if there is some sample code I could look at somewhere as a basis?

**Comment by branflake2267** [comment]
Nice job looking into it. 

I found this, it may be of interest.
https://stackoverflow.com/questions/17297308/how-do-i-resolve-the-actual-type-for-a-generic-return-type-using-reflection

**Comment by branflake2267** [comment]
I remember there being some Java Utils, not sure they fit this job, but there may be some utilities available somewhere. I always have to start looking around to confirm.

**Comment by seamusmac** [comment]
Cool, I didn't think to really use reflection. I was trying to use the JDT api as much as possible. 
There is the JavaModelSearch util class in there, but nothing for generics, unfortunately

Do you want me to try with the reflection based approach then?

**Comment by branflake2267** [comment]
I think you could use whatever works. That said, you're heading in the right direction, thinking about using what's available. You can only use the libraries available on smallest installs or target machine. If you're running a target you're safe to test using the dependencies. It's safe to use reflection because it's part of the Java JDK api. You can add libraries in the manifest for use as well. I think there may be an older guava library loaded on the classpath if that makes it easier to use some higher level utility to get the job done. Anyway running debugging against the target makes it hard to add a reference to a library that wouldn't be on an end user machine. But if you don't have all that set up, keep it simple to start. Or I can provide directions on how that might be done.

**Comment by seamusmac** [comment]
Some credit goes to @stephan-herrmann for answering my question related to JDT on this.

See https://stackoverflow.com/questions/49117612/eclipse-jdt-core-resolve-generic-return-type-for-parameterised-super-method

**Comment by stephan-herrmann** [comment]
Please keep in mind that all code in "internal" packages of JDT **may change without notice**. As the development of support for Java 9 showed, this is more than a theoretical risk, changing method signatures etc is a reality, necessary for keeping pace with the evolution of Java. On stackoverflow I intentionally said "For further _inspiration_ you may want to look that the internal method ...". In this particular case I would actually recommend to copy the relevant method(s) into your own code. The amount of code to copy should be low (it's all coded against public API) - compared to the risk of breakage.

**Comment by branflake2267** [comment]
Good point, I've already seen breaks because of internal api usage.

**Comment by stephan-herrmann** [comment]
JDT has a rich API, so that access to internal methods should not be necessary. If for whatever reasons this API is not sufficient for your needs, it's always a good idea to file a request in our bugzilla - hoping that we can always find some solution avoiding any access to internals.

**Comment by seamusmac** [comment]
I didn't really look at the package when I coded the solution for this bug. I was trying to make the change as small as possible and rather that copying code from JDT, I tried to use what was available.

If you want me to copy the code in question here to remove the internal package dependency, let me know and I can submit another PR.

Is the PR that was merged, already in the snapshot build or ?

**Comment by branflake2267** [comment]
It's merged, but haven't staged it. But after looking at it again, it looks like it's setting the parser to Java 8, do you know if that will be a problem for folks using Java 7?

**Comment by branflake2267** [comment]
I think some configurations may have Java 8 for Oxygen and Java 7 possibly as the application runtime. And in some cases possibly Java 6.

**Comment by branflake2267** [comment]
Deployed to staging.

**Comment by seamusmac** [comment]
@branflake2267  Thanks a million for that, I installed the snapshot version you deployed yesterday. It all looks good so far. I even updated to Oxygen.3. No problems what so ever :)

**Comment by branflake2267** [comment]
Great to hear. Thanks for the feedback. Would you like to announce there's a fix on staging if you want to try? I like to wait a week or so before pushing to the production version. I'll schedule building for production next week.

**Comment by seamusmac** [comment]
I see that this has still not been released. My team of 6 people has been using the snapshot version since this fix went in. There has been no reported problems so far. 

Is there a plan to release this any time soon?

**Comment by branflake2267** [comment]
Awesome thanks for reporting! 

I usually like to take a week before I release it to production. I've got a large set of projects I work on as well, and like to dog food the changes my self. I can schedule pushing the update to the production repo next week.

**Comment by seamusmac** [comment]
@branflake2267 Any sign of this being released. I had a developer just install from marketplace, and the version was from last year. 3.0.0.201710131939
