### ISSUE TITLE
target.tbd targets won't work on photon until patched

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#385]
Using target.tbd targets with photon has a bug. 

https://github.com/mbarbero/fr.obeo.releng.targetplatform/issues/76

**Comment by CrushaKRool** [comment]
Apparently it got fixed in their snapshot build now. :)

**Comment by protoism** [comment]
Photon is not a target anymore, and builds for newer targets seem ok. Closing
