### ISSUE TITLE
Update plans

### ISSUE THREAD

**Issue by mduggen** [gwt-plugins/gwt-eclipse-plugin#402]
Hi,

are there any plans to update the plugin to support latest eclipse version 2021-12?

Best regards, mduggen

**Comment by keinhaar** [comment]
I got the Plugin working with the eclipse version 2021-12.
I've installed it from market place. After that gwt did not show up in preferences.
the error log showed a problem with the dependencies. i opened the gwt platform plugin jar and removed javax.servlet from Require-Bundle in the Manifest file. Replaced the file in the jar. then deleted org.eclipse.osgi folder from configuration. Started eclipse and its working now. gwt is visible in preferences, and my projects compile and run just fine.

**Comment by protoism** [comment]
A 4.0.0 release will be soon published
