### ISSUE TITLE
Support for Eclipse 2022-06. 

### ISSUE THREAD

**Issue by jreed-cartago** [gwt-plugins/gwt-eclipse-plugin#405]
Currently cannot install GWT plugin for 2022-06. It says it is missing dependencies. 

The error message in the log when attempting to installing the GWT Eclipse plugin is as follows

`java.lang.IllegalStateException: operation plan must be resolved
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCurrentJREOperation(ProvUI.java:338)
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:325)
	at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceWizard.lambda$5(MarketplaceWizard.java:876)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`

`Cannot complete the install because one or more required items could not be found.
  Software being installed: GWT Eclipse Plugin 3.0.0.201710131939 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 3.0.0.201710131939)
  Missing requirement: GWT Web Tools Maven Support 3.0.0.201710131939 (com.gwtplugins.gwt.eclipse.wtp.maven 3.0.0.201710131939) requires 'osgi.bundle; org.eclipse.m2e.wtp 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: GWT Eclipse Plugin 3.0.0.201710131939 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 3.0.0.201710131939)
    To: org.eclipse.equinox.p2.iu; com.gwtplugins.gwt.eclipse.wtp.maven [3.0.0.201710131939,3.0.0.201710131939]`

**Comment by slavap** [comment]
It works for me when I do:

Add to "Available Software Sites" the following:

http://download.eclipse.org/mylyn/releases/3.25

http://download.oracle.com/otn_software/oepe/library/eclipse-oxygen.2
See https://stackoverflow.com/a/72897610/714136

**Comment by keinhaar** [comment]
The fix works for me.
Seems like the **mylyn project is dead**. 
Beginning with Eclipse-2022-06, it is no longer included in Eclipse Downloads, and is not on the download site https://download.eclipse.org/releases/2022-06/202206151000/
It has not been updated for 2 years now:
https://download.eclipse.org/mylyn/drops/

**Comment by niloc132** [comment]
I believe this can also be closed now, as part of the changes that went into #428?

**Comment by keinhaar** [comment]
I agree. Even if #428 only supports 2022-09 and newer.
