### ISSUE TITLE
Plugin com.gwtplugins.gdt.eclipse.platform requires javax.servlet as a bundle

### ISSUE THREAD

**Issue by axeluhl** [gwt-plugins/gwt-eclipse-plugin#422]
See https://stackoverflow.com/questions/72031131/gwt-plugin-fails-to-load-in-eclipse-2022-03-with-jdk-11-or-17-because-of-osgi-bu/74695821#74695821 for the resulting problems. The javax.servlet environment should be imported as packages instead.

**Comment by protoism** [comment]
Hi @axeluhl,
huge PRs have just been merged, and this issue, and linked PR https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/423 might be not relevant anymore.
Can you try this update site:
   https://eclipse.gwtproject.org.vertispan.com/2023-01-18/
and see if it fixes your problems?

**Comment by protoism** [comment]
Probably a duplicate of https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/408

**Comment by niloc132** [comment]
To confirm, will that change from javax.servlet to jakarta.servlet prevent existing javax.servlet projects from working properly? My understanding is "no", since gwt-dev's internal Jetty server is still using javax.servlet (and will be for the foreseeable future).

**Comment by axeluhl** [comment]
Works like a charm.

**Comment by protoism** [comment]
@axeluhl Thanks for testing!
PS what Eclipse version did you test on?

**Comment by axeluhl** [comment]
Sorry for not mentioning: 2022-12 for Eclipse Committers.

**Comment by protoism** [comment]
Thanks Axel.
You may want to candidate for https://github.com/gwt-plugins/gwt-eclipse-plugin/discussions/436 :)
