### ISSUE TITLE
Add support for GWT 2.10

### ISSUE THREAD

**Issue by niloc132** [gwt-plugins/gwt-eclipse-plugin#425]
The current plugin explicitly tests GWT 2.7-2.9, but doesn't yet support GWT 2.10.

Either as part of this ticket or another, it would be nice to pull and test latest HEAD-SNAPSHOT from sonatype-snapshots, to let us run nightly/regular builds to validate that nothing surprising has broken.

**Comment by keinhaar** [comment]
Why does this not work with GWT 2.10?
What is not working? 
Could you please clearify this.
I'm using GWT 2.10 with the OLD Plugin without issues. The 4.0 beta also works.

**Comment by protoism** [comment]
I think that this test is more about integration tests than on actual GWT SDK support.
As you wrote, the plugin seems to work with GWT 2.10

**Comment by cherio** [comment]
When gwt-2.10 is selected as the default library, the GWT Development Mode launcher configuration dialog does not display "Development Mode" panel with 2 radio buttons on the "GWT" tab (see screenshot below).

When gwt-2.9 is selected as the default library the panel shows up again. I can reliably make it disappear and reappear by changing the default GWT library.

![image](https://user-images.githubusercontent.com/2200569/234173075-1184e2ff-757e-48ab-a6e3-3b0f23d2e60f.png)

**Comment by keinhaar** [comment]
Solved with 4.1.0_RC2
