### ISSUE TITLE
Run tests (and possibly build?) with Java 11

### ISSUE THREAD

**Issue by niloc132** [gwt-plugins/gwt-eclipse-plugin#426]
There are warning lines in the logs about Java 11 not being available:

```
[WARNING] Using JavaSE-17 to fulfill requested profile of JavaSE-11 this might lead to faulty dependency resolution, consider define a suitable JDK in the toolchains.xml
```

It would be a good idea to at least test with Java 11, if not actually perform the build.

**Comment by protoism** [comment]
I'm not sure that this is possible, as the build depends on m2e 2.0 which is built with JDK 17 compatibility (bytecode version 61.0).
While Eclipse should require JDK11, plugins may use up to JDK17. And they do.

Incredibly enough, we're ok with target JDK 11 (bytecode version 55.0): the way we're interacting with m2e APIs objects does not require any record specific bytecode.

But as soon as soon as we do even silly operations, such as invoking a System.err.println on a m2e record, the compilation fails: the compiler says that some code the plugin depends on (i.e. m2e) uses records, which are not available in JDK 11, which is our target (note: a more tolerant compiler would be very useful in this case!)

So... the situation is far from clean, but the only clean solution I can think of is generating two versions, one for m2e 1.x (I believe Eclipse <= 2022-06), and the other for >= 2022-09. Which is simply not worth it.

**Comment by protoism** [comment]
Eclipse requires JDK 17 since 2022-09.
No plan to support 2022-06.
Closing
