### ISSUE TITLE
Is the GWT Plugin being officially discontinued?

### ISSUE THREAD

**Issue by CalculonPrime** [gwt-plugins/gwt-eclipse-plugin#431]
Someone posted that on the GWT Users group.

I take it this is not the official site of the GWT Plugin?  Do you know why it's being discontinued?  Also, from the other issues I saw here, it looks like it may have disappeared off the marketplace due to an account lockout, but was Google itself locked out, or you, the guy running this github project?

Also, can you enable Github discussions for this project so we don't need to open issues to ask questions?

**Comment by keinhaar** [comment]
No, it is NOT discontinued. There is currently some action to make the plugin compatible with current eclipse versions.
Most of the discussion is here https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/406, or on gitter. You will find at least 2 update sites with beta versions.

**Comment by niloc132** [comment]
Discussions enabled, I'll close this issue now that it has been answered.

It is our intention to have version 4.0 released by the end of next week, supporting newer GWT and Eclipse.
