### ISSUE TITLE
2022-12 and 2022-09, will they be supported?

### ISSUE THREAD

**Issue by jreed-cartago** [gwt-plugins/gwt-eclipse-plugin#434]
Even though there is a pull request #409 to correct the problem of #407 there has been no Merge into deployment and it is hindering those of us using newer versions of Eclipse.

Are there any plans to merge this fix, or do I need to find another solution for debugging my GWT applications via the maven plugins themselves?

**Comment by niloc132** [comment]
Please don't open new issues when there are other open issues and pull requests that would be appropriate to reply to instead.

**Comment by jreed-cartago** [comment]
Thank you for your advice and we do use the Maven tools to run GWT for the most part, but when you have the need to run two GWT instances the maven project isn't enough and we then rely on this plugin to perform the debugging for the second GWT instance.

We are looking forward to your upcoming release.
