### ISSUE TITLE
The 4.0.0 Testbuild does not include SDBG

### ISSUE THREAD

**Issue by keinhaar** [gwt-plugins/gwt-eclipse-plugin#438]
The Testbuild does not include SDBG, which is an important part, because it allows debugging right out of eclipse.
In the last stable version it was included.

We should at least provide the option to install. On my [keeitsi](http://keeitsi.com/software/eclipse-plugins) test update site, i've used an composite repository to allow users to install both plugins at the same time.

It's easy to setup. I've attached the 2 nessesary files here from my test site as example (zipped, because xml files are not allowed here). Maybe we can do the same? But what about the Marketplace Entry? It also included SDBG.

[compositeSite.zip](https://github.com/gwt-plugins/gwt-eclipse-plugin/files/10577348/compositeSite.zip)

**Comment by protoism** [comment]
Hi @keinhaar, good find.
I wonder if it wouldn't be a bit cleaner to add a SDBG plugin to marketplace (I see you're heavily committing to it), and add a dependency from GWT Eclipse plugin to it, just to decouple releases.

**Comment by keinhaar** [comment]
@protoism 
that's why i have a composite update site on my keeitsi test repo. the 2 plugins are more or less independend from each other. 
can a dependency in the marketplace be optional? on the update site the user can still ignore SDBG, which is good in my opinion.
Anyway, i have no idea how to create a marketplace entry. any hint is welcome. 
The current State of SDBG is like the eclipse gwt plugin state. i will release version 2.0 shortly.

**Comment by protoism** [comment]
Hi @keinhaar,
I think it's better to go on without sdbg, but it will be shortly (say 4.1.0)

**Comment by keinhaar** [comment]
SDBG is now installable from Marketplace too.

**Comment by keinhaar** [comment]
SDBG is separated completely now
