### ISSUE TITLE
Failed Plugin Installation from Marketplace

### ISSUE THREAD

**Issue by igto83** [gwt-plugins/gwt-eclipse-plugin#440]
I am facing a problem with the installation of the plugin from the marketplace. 
The plugin is not downloading properly from http://storage.googleapis.com/gwt-eclipse-plugin/v3/release 

![image](https://user-images.githubusercontent.com/124736690/217366889-bdc08084-995b-43ca-8c01-24e3ffb8787e.png)

**Comment by protoism** [comment]
The plugin currently in marketplace is not compatible with recent Eclipse versions.

A good release candidate is here:

https://eclipse.gwtproject.org.vertispan.com/2023-02-01

More info here: 

https://github.com/gwt-plugins/gwt-eclipse-plugin/discussions/436
