### ISSUE TITLE
Super/Legacy Development Mode Radio Toggle missing for GWT 2.10.x

### ISSUE THREAD

**Issue by CalculonPrime** [gwt-plugins/gwt-eclipse-plugin#462]
When you have GWT 2.10.x selected for a project, then with the current v4.0.0 GWT Plugin, the radio button is missing/hidden.  The workaround is to switch back to GWT 2.9.x.  This may be due to code that attempts to parse the GWT SDK version as a float, and thus thinks the GWT version is 2.1, perhaps too old a version to be supported by the plugin.

My use case is that I have a custom linker and some resources that need to be initialized by starting up classic development mode, even though it's not supported by any current browser (you don't have open anything in a browser in my case case, just start up classic dev mode).  So I need to be able to toggle between the modes without having to revert back to GWT 2.9.x.  (For whatever reason, in Super Development Mode, the resource initialization doesn't work because of the emulated file system.)

**Comment by niloc132** [comment]
> My use case is that I have a custom linker and some resources that need to be initialized by starting up classic development mode, even though it's not supported by any current browser (you don't have open anything in a browser in my case case, just start up classic dev mode). So I need to be able to toggle between the modes without having to revert back to GWT 2.9.x. (For whatever reason, in Super Development Mode, the resource initialization doesn't work because of the emulated file system.)

Can you elaborate here? Legacy dev mode (it hasn't been "classic" for many years..) should not be necessary for testing linkers, and will break in very irritating ways even in htmlunit with Java 9+. I've recently been doing some linker development, and have not run into this issue, but if there is something to be addressed we should cover it over in the main GWT project.

**Comment by CalculonPrime** [comment]
The file system in SuperDevMode is emulated, so nothing you write will persist as far as I can tell.  I so I need to use classic mode to actually write to the file system.

**Comment by niloc132** [comment]
Can you be more specific? Are you writing private or deploy artifacts that shouldn't go out in the public directory, so the browser can't directly request them (nor can you see them on the codeserver)?

I'm assuming you've checked the workDir and launch directory? 

If none if this is helping, can you give a specific concrete example? As above, we haven't been having this issue in writing custom linkers for SDM and web workers the last few weeks. It could well be just a configuration issue, or not knowing what the directory should be...

**Comment by CalculonPrime** [comment]
Before I try to answer that, can you let me know whether the missing radio button is a bug or an intentional change?

**Comment by niloc132** [comment]
I strongly suspect it wasn't, but I am not all of the developers on this project, and we've inherited code that we don't always fully understand or agree with. I'm guessing bug, but will happily get back to you.

If you have a bug where linkers don't work, or are hard to debug, we'd love to have it over in https://github.com/gwtproject/gwt

**Comment by niloc132** [comment]
Yep here we are: 
https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/main/plugins/com.gwtplugins.gwt.eclipse.core/src/com/google/gwt/eclipse/core/launch/ui/tabs/GWTSettingsTab.java#L740-L748

**Comment by niloc132** [comment]
...and it turns out this has already been fixed, in https://github.com/gwt-plugins/gwt-eclipse-plugin/commit/ee474e516bc233eea521e9deff3fc18dfb3dea7e. We'll get a release out with it and other pending fixes soon.

**Comment by Kiiv** [comment]
Any update for this release ? Or maybe an available snapshot ?

**Comment by Kiiv** [comment]
latest nightly build seemed to be 02/24/2023 so this one is not available

**Comment by niloc132** [comment]
Thanks for checking, I'll look into it. We have a webhook setup, but it might not be behaving.

**Comment by Kiiv** [comment]
Any news about that ? Maybe an ETA for the next release or at least a new nightly ? :)

**Comment by cherio** [comment]
I confirm having the same issue. Radio buttons disappear and re-appear when switching the default GWT library to 2.10 and then back to 2.9.

![image](https://user-images.githubusercontent.com/2200569/234173732-402f84b2-ee09-4648-8ac8-a38dc3960614.png)

**Comment by protoism** [comment]
Hi @cherio, @Kiiv,
the nightly might be down, but CI artifacts are there:

    https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/4309290937

![image](https://user-images.githubusercontent.com/1098792/234733780-ab6d120b-aeff-4dbc-81a2-0ff9e90b114a.png)

BTW, if you're really interested in having this project maintained, please consider contributing (not on this one... already fixed :)

**Comment by niloc132** [comment]
Sorry about the nightly builds - I've manually pushed a nightly to the server now, and will try to get this working in an automated way soon.

**Comment by nowoe** [comment]
The nightly update site seems unreachable: https://plugins.gwtproject.org/eclipse/gwt-eclipse-plugin/nightly
Any chance for a 4.0.1 release?

**Comment by niloc132** [comment]
If you're referring to the message

> Document could not be loaded by browser.

that is only an error in the browser - that URL can be used in eclipse as an update site.

**Comment by nowoe** [comment]
Indeed I've tried the URL in the browser, thank you.

**Comment by protoism** [comment]
This issue is fixed in main since a while.
Now we have a release candidate, so I think that this issue can be safely closed

4.1.0rc1 It is downloadable here:

https://github.com/gwt-plugins/gwt-eclipse-plugin/releases/download/v4.1.0-rc1/gwt_eclise_plugin_v4.1.0_rc1.zip

Not long before publication on the store
