### ISSUE TITLE
Plugin 4.0.0 / Run Configuration / Not producing SuperDev

### ISSUE THREAD

**Issue by eliasbalasis** [gwt-plugins/gwt-eclipse-plugin#469]
On Eclipse 2023-03 with GWT Eclipse Plugin 4.0.0,
clicking on a Maven project with GWT support
and then creating a GWT Run Configuration from it,
in GWT section, the Development Mode choice is not displayed.

Also, the resulting Run Configuration is not SuperDevMode based, containing the "-nosuperDevMode" parameter.

This is only reproducible when the project is equipped with GWT 2.10.0

No issues with GWT 2.9.0 though.

![image](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/1681838/b2aa3994-37fa-406c-955d-29fbb092aeb6)

Strangely, the "Run As" >> "GWT Development Mode with Jetty" action is producing a proper SuperDevMode Run Configuration.

**Comment by eliasbalasis** [comment]
I am guessing this is due to the deprecation of legacy DevMode.

**Comment by thebia** [comment]
I installed the nightly build linked in this comment https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/462#issuecomment-1524351076 and it seems to solve the problem.

**Comment by eliasbalasis** [comment]
I confirm, the nightly build works
4.0.1.202302241744
