### ISSUE TITLE
Is there a tutorial here on how to install the plugin in Eclipse?

### ISSUE THREAD

**Issue by justinjalandoniTI** [gwt-plugins/gwt-eclipse-plugin#472]
I know that you can install the plugin via eclipse marketplace. Is there a tutorial on how to install the plugin through the plugin in this repository?

**Comment by justinjalandoniTI** [comment]
Hello, that's probably what I am looking for. I will try it. I would like to confirm which file should we download among these: 
![Uploading image.png…]()

**Comment by protoism** [comment]
repository.zip is the file you're looking for.

**Comment by protoism** [comment]
I'll close the ticket.
Just reopen if the issue is not solved
