### ISSUE TITLE
Unable to create run configuration for super dev mode

### ISSUE THREAD

**Issue by rdeangelis83** [gwt-plugins/gwt-eclipse-plugin#476]
Steps to reproduce:

- Install GPE in Eclipse 2023-09
- Create a new GWT project (webAppCreator com.google.gwt.TestProject)
- Import created project
- Create a run configuration "GWT Development Mode (DevMode)"
In the "GWT" tab the "Super Development Mode" radio box is disabled
- Switch to the  "Main" tab
The "Project" and "Main class" will be filled out automatically
Main Class: com.google.gwt.dev.DevMode
- Switch back to the "GWT" tab to enable super dev mode
-> The option disappered

See attached screenshots
 
![image (1)](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/1331961/1313af47-8b03-44c1-98bf-7d91d9d56ae0)
![image (2)](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/1331961/a04201ae-7a56-402e-b3c7-b3703fedd8fb)
![image (3)](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/1331961/ea54f34a-7f34-4bc3-a722-202ca1cf697e)

**Comment by protoism** [comment]
Hi @rdeangelis83 sorry for the late answer.
I really can't replicate this issue (with Eclipse 2023-12).
Are you still affected?

**Comment by protoism** [comment]
This issue should be solved by upcoming 4.1.0.
The PR is https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/459
