### ISSUE TITLE
Update to GWT 2.11

### ISSUE THREAD

**Issue by niloc132** [gwt-plugins/gwt-eclipse-plugin#478]
Now that GWT 2.10.1 and 2.11.0 have been released, this plugin should default to GWT 2.11, and be tested with it as well.

**Comment by ddevlabs** [comment]
May I ask what is left to be done to get this released? 

Never worked on eclipse plugin development before, but open to help with this when given some guidance.

It's still not possible to get the plugin installed on Eclipse, and the workaround proposed in the other duplicate issues don't work due to the link for download not being available

**Comment by protoism** [comment]
Hi @ddevlabs,
Honestly not much is missing: just adding GWT 4.11: releasing without it makes no sense.
So... if you're willing to contribute, I'd be glad to give guidance, even though I'm no expert on Eclipse plugins either (but somehow we managed to make a release ;-)

**Comment by ddevlabs** [comment]
@protoism 

> Hi @ddevlabs, Honestly not much is missing: just adding GWT 4.11: releasing without it makes no sense. 
>> 
I don't quite understand this.  Can you please elaborate?

> So... if you're willing to contribute, I'd be glad to give guidance, even though I'm no expert on Eclipse plugins either (but somehow we managed to make a release ;-)
>>
Yes, I'm willing to contribute and open to learning, so sounds like a plan - let's make it happen.

Just fyi: I already successfully got it working on the latest Eclipse by doing a checkout and building it locally myself, so I don't imagine that it would be too much of a hassle to get the latest gwt sdk integrated, then make a public release.

![Screenshot 2024-06-22 at 07 38 36](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/138258234/2e147252-aaf7-41e9-b990-65db31abbc9d)

![Screenshot 2024-06-22 at 07 31 02](https://github.com/gwt-plugins/gwt-eclipse-plugin/assets/138258234/76968a65-b606-4c5e-aaec-c79f2034cfbf)

**Comment by protoism** [comment]
@ddevlabs: feel free to PM me on gitter https://matrix.to/#/@protoism-5be4afbdd73408ce4fae5106:gitter.im for possible ways of contributing.
(I hope the URL is correct)
