### ISSUE TITLE
Installation fails on Eclipse 2023.12

### ISSUE THREAD

**Issue by johnthuss** [gwt-plugins/gwt-eclipse-plugin#480]
The plugin won't install on the current Eclipse version 2023.12 because the plugin for java.inject is missing. It fails with this error:
requires 'osgi.bundle; javax.inject 1.0.0' but it could not be found

I was able to copy these two files over from a previous Eclipse installation and then I could install the GWT Plugin:
/Applications/Eclipse.app/Contents/Eclipse/plugins/javax.inject_1.0.0.v20091030.jar
/Applications/Eclipse.app/Contents/Eclipse/plugins/javax.inject.source_1.0.0.v20091030.jar

**Comment by protoism** [comment]
The problem has been fixed on main branch
You may use the CI artifacts.

This is the build:
https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7872612432

This is a direct link to a downloadable repository
https://github.com/gwt-plugins/gwt-eclipse-plugin/actions/runs/7872612432/artifacts/1238411002

Here a link on how to install from zip file
https://stackoverflow.com/questions/5482554/how-to-install-plugin-for-eclipse-from-zip
