### ISSUE TITLE
Fresh install of the plugin in Eclipse 2024-03 is missing dependencies

### ISSUE THREAD

**Issue by cherio** [gwt-plugins/gwt-eclipse-plugin#482]
In a freshly installed instance if Eclipse 2024-03, GWT Plugin fails to install complaining on missing dependency:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 4.0.0.202302020242)
  Missing requirement: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.gdt.eclipse.suite 4.0.0.202302020242) requires 'osgi.bundle; javax.inject 1.0.0' but it could not be found
  Cannot satisfy dependency:
    From: GWT Eclipse Plugin 4.0.0.202302020242 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 4.0.0.202302020242)
    To: org.eclipse.equinox.p2.iu; com.gwtplugins.gdt.eclipse.suite [4.0.0.202302020242,4.0.0.202302020242]
```
The well familiar status message "Cannot perform operation. Computing alternate solutions" appears during install but eventually the process throws the towel.

The Eclipse flavor used is "Eclipse IDE for Enterprise Java and Web Developers". It is up to date and has no other plugins or extensions installed.

**Comment by eliasbalasis** [comment]
see https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/480

**Comment by cherio** [comment]
The recipe of simply copying "javax.inject_1.0.0.v20091030.jar" to the "plugins" directory from an older instance of Eclipse allowed the install to complete successfully.

Thank you!
