### ISSUE TITLE
GWT Designer

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#56]
First stage investigate GWT Designer

**Comment by slavap** [comment]
By the way, it could be easier just to reuse javafx scene builder. It's possible to provide set of custom widgets for SceneBuilder (as java classes in jar), then all visual tooling will just work, and as result we'll get xml (very close to ui.xml by structure).

**Comment by branflake2267** [comment]
I did a quick overlook and looks like the compiler implementation would have be replaced with SDM.

**Comment by slavap** [comment]
There is a patched version of GWT designer for 2.7.0, so may be it makes sense to contact author of this patch.
https://groups.google.com/forum/m/#!topic/google-web-toolkit/hQrUnLNkXVM

**Comment by branflake2267** [comment]
Oh nice. 
https://github.com/bently0602/GWT-2.7

**Comment by branflake2267** [comment]
Closing as won't fix.

**Comment by slavap** [comment]
That's sad :-( Designer is quite useful for RAD development. Though GWT designer was never good enough :-(

**Comment by branflake2267** [comment]
Yeah I know. I agree. But I don't have enough time. So I'll wait till someone steps up to bat to do it. :(
