### ISSUE TITLE
No CodeServer launched after Tomcat start

### ISSUE THREAD

**Issue by dodgex** [gwt-plugins/gwt-eclipse-plugin#65]
Hello there!

I just wanted to test this plugin and followed the steps from [this video](http://gwt-eclipse-plugin.github.io/gwt-eclipse-plugin/eclipse/servers/Tomcat.html#Launching). But when i started the Tomcat from eclipse, there where no superdev code server started. the only difference i could spot is that i'm using tomcat 7 instead of 8.

i followed the steps from the video and rechecked everything multiple times, even when i manually create a run configuration for the code server and name it `gwt-my-context-name` (assuming it tries to find a run configuration with `gwt-` prefix) it does not start it.

when i start both manually it works like a charm, but it would be nice to start both together. :)

any idea what i might have done wrong?

**Comment by dodgex** [comment]
for some reason the plugin just decided to start the code server. i have absolutely no idea what might have changed.

**Comment by branflake2267** [comment]
I think this issue is related to another issue on ubuntu. I found the issue and working on it. The GWT Nature isn't getting turned on b/c it's using the facet. At least thats one of the issues I found and fixed last night. I'm testing it tonight, but this is legit. .

**Comment by branflake2267** [comment]
Which OS are yo using?

**Comment by dodgex** [comment]
Eclipse 4.4.2 on Windows Server 2008 R2 Standard x64

**Comment by branflake2267** [comment]
Thank you for reporting.

**Comment by branflake2267** [comment]
If you have time, could you confirm something? I have a feeling it says this on your launcher. `Project does not use GWT or GAE`

 Go to the debug configurations, find the GWT SDM Code Server launcher and see if it says
![screen shot 2015-05-15 at 7 46 35 am](https://cloud.githubusercontent.com/assets/1326504/7655170/99f29f9e-fad6-11e4-958d-c02f3d1c2fb0.png)

**Comment by dodgex** [comment]
it does *not* show the message. and as i mentioned, the plugin started to work correctly at some point after restarting both the codeserver and tomcat some times (maybe i even restarted eclipse between that but i'm not sure about that).

**Comment by branflake2267** [comment]
oh ok, sounds good. The nature got turned on, on another route then.

**Comment by branflake2267** [comment]
Can you update the plugin and try it again?  Delete the code launcher and then start the server which will create a new code launcher.

**Comment by dodgex** [comment]
it creates a launch config, but that does not work due to the `src/main/resources` [issue](https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin/issues/66).

so i think this one is ok now.

**Comment by dodgex** [comment]
but: it seems to only work if i start the tomcat from the servers tab. when using the the launch configuration via the run icon in the toolbar it does not start the CodeServer.

and also: is there a way to restart the tomcat, without restarting the CodeServer? although we are currently evaluating jrebel there will still be some situations where we would need to restart the server part

Thanks :)

**Comment by branflake2267** [comment]
There is a way to restart the server without restarting the code server. By default it restarts the code server. This can be turned off in the project properties menu > filter facet > goto gwt facet, disable the sync.

**Comment by dodgex** [comment]
The problem is, that option does not start the CodeServer when starting the tomcat. 

It might be a first world & lazy dev problem, but imo it would be nice to start them together but be able to restart the tomcat without the code server. (maybe even stop both when the code server is stopped? - not sure about this one).

feel free to decide about this if you might think that is a good idea and the need effort is reasonable. if you think it is not worth implementing, i'm ok with this... as i said: first world problem. hitting play twice shouldnt hurt that much . although the feature to start both is one of the things that make this plugin better than the original one. ;)

**Comment by dodgex** [comment]
Update: with this option turned off, it does not start the CodeServer together with tomcat, but it still stops it when stopping the tomcat :/

**Comment by branflake2267** [comment]
oh yeah, that is a bug. Nice find.

**Comment by branflake2267** [comment]
https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin/pull/71 - fix on its way, waiting for build server...

**Comment by dodgex** [comment]
i just realized that this issue is still open. at least with the latest version (just updated all of my plugins) it starts both now when starting the tomcat.

but still it kills the SDM when i stop/restart the tomcat. as mentioned [here](https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/65#issuecomment-104150988) it might be a nice feature to be able to restart the tomcat without restarting the SDM.

**Comment by dodgex** [comment]
and sadly it seems that your fix in #71 is broken :/

It still kills the SDM when sync is disabled
![image](https://cloud.githubusercontent.com/assets/204013/8977679/88a63006-369b-11e5-9b62-f52e62fc6a3b.png)

**Comment by dodgex** [comment]
eclipse 4.4.2
gwtplugin version: 0.0.0.201507300611

**Comment by branflake2267** [comment]
I added something to turn off the sync. Would this work for you. Goto project properties then to gwt facet settings. 

![screen shot 2015-07-30 at 7 47 10 am](https://cloud.githubusercontent.com/assets/1326504/8986077/48ce5d0c-368f-11e5-86e0-09deaf75222c.png)

**Comment by dodgex** [comment]
I know this option. And even if this is unchecked it kills the SDM.

**Comment by branflake2267** [comment]
Gotcha, something to fix then.

**Comment by dodgex** [comment]
maybe while you are on it, you could add an option to start both together, but allow to restart the tomcat without restarting the SDM? or should i open a new issue for that? :)

**Comment by branflake2267** [comment]
Could you create a new issue for that request?

**Comment by branflake2267** [comment]
I've got a fix for killing sdm on server termination coming...
