### ISSUE TITLE
modules not detected when in src/main/resources

### ISSUE THREAD

**Issue by dodgex** [gwt-plugins/gwt-eclipse-plugin#66]
It seems that the plugin only searches for `.gwt.xml` files inside `src/main/java`. We have for most of our projects our `.gwt.xml` files inside `src/main/resources` but those are not found in the _Run Configurations_ configuration. Only if i move then to `src/main/java` they are found/available.

**Comment by branflake2267** [comment]
I've been wondering about this too. Does this happen in GPE too?

**Comment by dodgex** [comment]
hey i left the office right after opening this issue. if it is ok i'll check on monday on one of our other eclipse installations.

**Comment by branflake2267** [comment]
I was curious no hurry.

**Comment by metteo** [comment]
I think this might be related to the way how m2e handles src/main/resources. It adds exclude for that src folder. Something like */**. If you remove it, gwt.xmls should be detected.

**Comment by branflake2267** [comment]
I forget, the source paths for resources, or any other paths, m2e sets up to excludes by default. I remember thinking this is annoying because I want them included in the build path.

**Comment by branflake2267** [comment]
Adding some notes. m2e default configuration is to exclude resources directory from the build path. 
![screen shot 2015-05-18 at 9 03 24 pm](https://cloud.githubusercontent.com/assets/1326504/7695264/bf364fee-fda1-11e4-8eea-9b99507ca141.png)

**Comment by branflake2267** [comment]
https://www.eclipse.org/m2e/documentation/m2e-faq.html - resources are excluded by default can be found here. I should configure the maven builder include these.

**Comment by branflake2267** [comment]
https://github.com/gwt-maven-plugin/m2e-gwt - could integrate this feature, or use it to solve it...

**Comment by branflake2267** [comment]
I'll aim to add the lifecycle goals to the import process just for this particular maven plugin.

**Comment by branflake2267** [comment]
https://github.com/tbroyer/gwt-maven-plugin/blob/master/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml - Broyer's plugin lifecycle...

**Comment by branflake2267** [comment]
mvn gwt:resources or the resource mojo copies the files into the web-inf/classes directory. This isn't in the classpath so it's a problem still. I did notice that target/generated-sources gets set up as a source folder on a second maven update and if it were copied to this folder could work. m2e-gwt plugin doesn't do much in this case. I'm going to push the priority down on this because there are a couple workarounds in the meantime.

**Comment by geoffreywiseman** [comment]
Colleague got bit by this recently -- any change?
