### ISSUE TITLE
Eclipse 4.5 Support (Mars)

### ISSUE THREAD

**Issue by joelhandwell** [gwt-plugins/gwt-eclipse-plugin#77]
I used current update site and successfully installed gwt-eclipse-plugin, and I tried to create Web Application Project (GWT enabled, GAE disabled).
While creating Project, Eclipse Crushed leaving following directory structure in workspace:

ProjectName -- .settings      -- org.eclipse.jdt.core.prefs
                         bin              -- (empty directory)
                         src              -- (empty directory)
                         .classpath
                         .project 

I was aware that GPE was stated for 4.4 while installation, so I expected that it would not be compatible, but for information creating this issue.

**Comment by branflake2267** [comment]
I'm using it with Mars, although I've noticed a couple minor issues, but hadn't noticed a failure with web app creation yet. Thanks for reporting.

**Comment by branflake2267** [comment]
Did it provide you with a stack trace?

**Comment by joelhandwell** [comment]
I tried to reproduce this again, and deleted project directory and created Web Application Project, and this time it was successfully created, though got following warning:

```
Unable to connect to http://localhost/update/compositeArtifacts.xml.
```

Session Data was like this:
```
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
```

I think we can take out bug label for this issue until other people reproduce.

**Comment by branflake2267** [comment]
It's not clean web app creation so I think it's ok leaving it as a bug for now. I'll try it out when I take another whack at bug squashing. Catching up with work after vacation so it will be a week till I triage. Thanks for the details.
