### ISSUE TITLE
Deployment Assembly Omitting Maven Dependencies with m2e-wtp 1.2.0

### ISSUE THREAD

**Issue by averigin** [gwt-plugins/gwt-eclipse-plugin#80]
The current release of the Google plugin for Eclipse appears to be incompatible with version 1.2.0 of the m2e-wtp plugin [which is required by version 1.6.x of the m2e plugin](https://bugs.eclipse.org/bugs/show_bug.cgi?id=438593). This will cause problems for Eclipse Mars users since it comes with m2e 1.6.1 and m2e-wtp 1.2.0 by default.

With m2e 1.6.1 and m2e-wtp 1.2.0 installed, running "Maven -> Update Project" adds a "Maven Dependencies" entry to my project's Deployment Assembly. However, as soon as I install the Google Plugin for Eclipse 4.4 (3.8.0.v201410302155-rel-r44), running "Maven -> Update Project" now removes the "Maven Dependencies" entry from the Deployment Assembly. This causes things to break in my normal web projects when I try to run them on Tomcat via "Run -> Run on Server".

I can manually re-add the "Maven Dependencies" entry to the Deployment Assembly, but as soon as I re-run "Maven -> Update Project" it disappears again. My interim solution: if use Eclipse Luna running m2e 1.5.2, m2e-wtp 1.1.0 and the Google plugin for Eclipse 4.4, everything works.

The minimal steps to reproduce this:
1. Start with a clean Eclipse Mars install.
2. Create a "Maven Project" (e.g., using the `maven-archetype-webapp` archetype).
3. Run "Maven -> Update Project".
4. Check the Deployment Assembly. It should contain the "Maven Dependencies" entry.
5. Install the Google Plugin for Eclipse 4.4 ([link](https://dl.google.com/eclipse/plugin/4.4)).
6. After restarting Eclipse, run "Maven -> Update Project".
7. Check the project's Deployment Assembly. It should no longer contain the "Maven Dependencies" entry.

**Comment by branflake2267** [comment]
I consider the Google Plugin for Eclipse the source of this fork. I renamed this to the GWT Eclipse plugin. Are you saying this plugin doesn't work with m2e-wtp or the original source? If you're referring to the original source, I'm going to say I'm no longer helping maintain that because I don't have enough time to help on it.

**Comment by averigin** [comment]
The issue is with with the original source.

**Comment by rduerig** [comment]
Well I'm actually facing the same issue as @averigin with the current release of this plugin. I manually uninstalled the original google plugin and installed this plugin via http://storage.googleapis.com/gwt-eclipse-plugin/release.
However, steps 6 and 7 stay the same. I'm still losing "Maven Dependencies" in Deployment Assemblies.

Configuration:
- m2e 1.6.1
- m2e-wtp 1.2.0
- Google Plugin 0.0.0.201508031545

**Comment by branflake2267** [comment]
Sounds like a bug. I like wtp and aimed at getting things running better with it. I could use a test project that I could import and test with the steps to recreate the issue. Would you be able to provide a test project?

**Comment by rduerig** [comment]
Thanks for the reply.
As @averigin wrote in the first post there is a minimal setup to reproduce the problem:
>The minimal steps to reproduce this:
1. Start with a clean Eclipse Mars install.
2. Create a "Maven Project" (e.g., using the maven-archetype-webapp archetype).
3. Run "Maven -> Update Project".
4. Check the Deployment Assembly. It should contain the "Maven Dependencies" entry.
5. Install the Google Plugin for Eclipse 4.4 (link).
6. After restarting Eclipse, run "Maven -> Update Project".
7. Check the project's Deployment Assembly. It should no longer contain the "Maven Dependencies" entry.

I will try to provide a testproject by doing those steps. The issue happened with production code I cannot export. Would be really nice to be able to use Mars for work, atm I'm stuck at Kepler.

**Comment by rduerig** [comment]
I created a sample project with the maven-archetype-webapp as described above.
See https://drive.google.com/file/d/0B2_OS4jFWgOGLW55MUl0Z05OQUE/view?usp=sharing for the compressed project files.
And I tested a bit with that project:
- First thing I did was manually adding "Maven Dependencies" to the deployment assemblies.
- By default a junit dependency was included in the pom, with test scope. I changed the scope to default by removing that line <scope>test</scope>.
- I deployed the Sample webapp to my tomcat server (Tomcat 6 btw).
- The wtp plugin now deployed the junit jar under WEB-INF/lib on my tomcat.
- Now I selected Properties - Maven - Update Project on my Sample project.
- After that I checked Properties - Deployment Assemblies and "Maven Dependencies" disappeared.

Again, it would be really nice if you could check that ^^
And please inform me if I did anything wrong with the above link to the project archive.

**Comment by branflake2267** [comment]
Thanks for the directions and project! I'll try that out soon. I've got a deadline at work which is sucking up all my extra time although we should be over that hump in a couple weeks and I can resume. I'm aiming to get some bug fixes and enhancements done before the winter conferences.
