### ISSUE TITLE
ClientBundle resource files not found in public

### ISSUE THREAD

**Issue by johnthad** [gwt-plugins/gwt-eclipse-plugin#87]
I have a large webapp that began life with GWT 1.X. The app's images (PNGs) are stored in `[module-path]/public/images`, the client code in `[module-path]/client`, etc. Early in 1.X, this was how it was done. When ClientBundle's came along the images stayed put. This worked well since the application and its online users manual could share the same icons, etc.

With the current gwt-eclipse-plugin, I get a missing resource errors on _all_ of these @Source image files, although the Java build path includes all files in src. To get around this I must set _Preferences -> Google -> Errors/Warnings -> GWT Client Bundle -> Missing resource file_ to _Warning_ or _Ignore_, but this makes it hard to spot real errors.

I'd rather not have to move over 100 images. This webapp is pretty stable and widely deployed. Moving the images inside `[module-path]/client` would also require changes to a lot of DocBook code.

**Comment by branflake2267** [comment]
Could you provide a test project to work off of? I've seen this before but it's been awhile.

**Comment by johnthad** [comment]
Thanks, Brandon. A sample project is at https://github.com/johnthad/gwt-clientbundle

**Comment by branflake2267** [comment]
Thank you! I've got a couple a deadline at work so I'm bound up at the moment, but I'll aim to get this in the next round, which I have planned after this deadline.

**Comment by johnthad** [comment]
Out of curiosity, where are the settings for *Google Classic* stored? On the project where the problem first appeared, however many times I uncheck *Properties for [project] -> Google Classic -> GWT Classic -> Use Google Web Toolkit* and press *OK*, the setting *always* turns back on. I thought that if it is not getting saved correctly, I might edit the settings file with Eclipse closed in hopes that it will take.

**Comment by branflake2267** [comment]
I suspect that is in the plugin package name directory in the meta directory. I'm not sure I haven't looked.

**Comment by branflake2267** [comment]
This might be fixed with the other resource fix.

**Comment by branflake2267** [comment]
It's fixed, and should be in staging soon. 
![screen shot 2017-03-02 at 3 55 25 pm](https://cloud.githubusercontent.com/assets/1326504/23532523/b75530b6-ff60-11e6-9e55-b41311eba5ae.png)
