### ISSUE TITLE
"-noSuperDevMode" parameter is removed from .launch files automatically (GWT 2.8)

### ISSUE THREAD

**Issue by eguimerans** [gwt-plugins/gwt-eclipse-plugin#88]
While testing initial snapshot of GWT 2.8, I realized that "noSuperDevMode" parameter in launch profiles is deleted automatically when changing between GWT 2.7 to GWT 2.8.  Can you confirm this will be final behaviour? 

Test is easy:
If you create a new Google Web Application Project from eclipse and check "Generate project sample code" you can see it easily.  I've just runned in devMode and in superDevMode with gwt 2.7 and everything's fine. Then copied the generated launcher's code to new launch files and added to the project to customize, and update classic-devMode launcher with "-noSuperDevMode" parameter. Everything keeps working fine, but when changing the project to GWT 2.8, this param is automatically removed.

![gwt-nosuperdevmode_error](https://cloud.githubusercontent.com/assets/8386878/9555920/ad161d74-4d9e-11e5-9110-59fa4508d7e4.jpg)

(If need to post repository with the project, let me know)

Thankx,

**Comment by branflake2267** [comment]
I'll be investigating and see why this is in the upcoming week.

**Comment by branflake2267** [comment]
I think a fix is in the works for this. Could I get a link to where you are getting the GWT 2.8 nighty sdk?  Or did you compile it locally? If so could I get a copy of that? I'm looking for a way to verify this fix.

**Comment by skarzhevskyy** [comment]
For this tests we used August version of SDK  2.8 gwt-2.8.0-20150805.zip
http://repository-m2.pyx4j.com/com/google/gwt/

I just took  the files from here on august.
https://oss.sonatype.org/content/repositories/google-snapshots

**Comment by branflake2267** [comment]
Thank you!

**Comment by branflake2267** [comment]
Looks like the patch I've got fixes it. I've got a couple more things I'm aiming for then I'll merge and build the nightly for testing.

**Comment by skarzhevskyy** [comment]
Hi Brandon 
 Got a build 201509290133, Close, Open GWT Project -> .launch changes, -nosuperDevMode removed
 Is it correct build ?

**Comment by branflake2267** [comment]
It would be in the latest snapshot repo. I uploaded in the last couple of days. I'm hoping it's fixed. :)

**Comment by branflake2267** [comment]
Is it failing still?

**Comment by skarzhevskyy** [comment]
Yes. The same problem with gwt 2.8.

**Comment by foal** [comment]
May by for the same (unknown) reson as a -port parameter in the issue #94?

**Comment by branflake2267** [comment]
I haven't been able to replicate this behavior in my configurations with GWT 2.8, although I'll aim to try again.

**Comment by branflake2267** [comment]
I've replicated the issue and fix is on it's way in.
