### ISSUE TITLE
allow to restart tomcat without stopping SDM

### ISSUE THREAD

**Issue by dodgex** [gwt-plugins/gwt-eclipse-plugin#90]
It would be nice if it would be possible to start the SDM together with the tomcat, but allow to restart the tomcat without also stopping the SDM.

This would allow to reload the serverside without having to also do a full compile for the client side again.

(see: https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/65#issuecomment-104150988)

**Comment by freddyboucher** [comment]
If I'm correct, GWT 2.8 SNAPSHOT stores the compilation so when you restart your servers, it doesn't fully recompile the project.
So the feature you are requesting wouldn't be really useful.

**Comment by dodgex** [comment]
@freddyboucher you are correct. not sure if it is already implemented but at least they mentioned that the want to to that.

but i see two points still making this feature usefull
1. we all know how long a release could take... somehwere in gwt-contributors group i read that 2.8 was planned to be released late 2014. now its late 2015.
2. depending on how long it will take to start the SDM it might still be interesting.

i don't know how much work it would be to implement that feature but i think this still could be usefull if not too hard to implement

**Comment by branflake2267** [comment]
Good idea

**Comment by foal** [comment]
May be I am wrong, but I just call "Publish" from server (Tomcat) context menu to reload the serverside changes.

**Comment by branflake2267** [comment]
Fixed in GWT Eclipse Plugin V3
