### ISSUE TITLE
CodeServer wipe out the -port parameter on edit launch configuration 

### ISSUE THREAD

**Issue by foal** [gwt-plugins/gwt-eclipse-plugin#94]
I need to run two GWT app user and admin. The standard launch config for GWT code server use port 9876 so there is a conflict between two applications.

I add the -port 9877 parameter to second application and it works, but only while first edit the updated launch config. 

It is easy to reproduce. 

1. Open any CodeServer launch to edit
2. On Arguments tab add -port 9877 parameter
3. Save the config. Now the Codeserver will use 9877 port - it is Ok
4. Open the CodeServer launch to edit
5. Go to Arguments tab. The parameter -port disappears - there is an error :)

**Comment by branflake2267** [comment]
Sounds like one of the launch processor paths needs tuning. It's beeing greedy.

**Comment by branflake2267** [comment]
SuperDevModeCodeServerPortArgumentProcessor would be at fault if there is an issue.

**Comment by branflake2267** [comment]
Fix on its way... https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/125

**Comment by branflake2267** [comment]
The next snapshot will have it later tonight, once I upload it.

**Comment by branflake2267** [comment]
![screen shot 2015-12-29 at 12 14 58 am](https://cloud.githubusercontent.com/assets/1326504/12031470/3bc173b6-adc1-11e5-8ff8-0c10fc5c833f.png)
![screen shot 2015-12-29 at 12 15 06 am](https://cloud.githubusercontent.com/assets/1326504/12031471/3cb7b8a2-adc1-11e5-8de2-275f7a1b6fb5.png)
