### ISSUE TITLE
Missing Gui for "Runtime Options" 

### ISSUE THREAD

**Issue by andyx1975** [gwt-plugins/gwt-eclipse-plugin#99]
Hi,

if you are using a KDE Desktop (Kubuntu or Linux Mint) as client... you can not edit the "Run Configuration" with this plugin. Most of the tabs in the option mask remain grey (see screenshot). This happens with latest eclipse mars (Luna is working). Even with a fresh installation.

![runtimeconf](https://cloud.githubusercontent.com/assets/15858063/11169276/30d6c7ce-8bb3-11e5-94cb-73099959a1ea.png)

Thanks 
Andy

**Comment by branflake2267** [comment]
Thanks for reporting.

**Comment by branflake2267** [comment]
Do you know if this happens on Ubuntu?

**Comment by andyx1975** [comment]
Sorry but I never really used gnome, cinammon or xfce... I guess it is KDE related.

**Comment by andyx1975** [comment]
So you can reproduce this bug?

**Comment by branflake2267** [comment]
The challenge is I'm running out of VM room on my laptop, although I've started cleaning the hard drive on the last round of fixes to see if I could make more room for another. 6 vms are sucking up my hard drive space. I've tested it on ubuntu/gnome and it works for me. I'll see if I can get KDE setup on ubuntu I'm using. 

If I can't produce it in ubuntu with kde, can you provide steps for me to create a VM with your configuration and the links to the OS image I'd need to download to install it? I'm using parallels just in case you find something easy to install with it.

**Comment by branflake2267** [comment]
Looks like it should be easy for me to install KDE: http://askubuntu.com/questions/452083/how-to-install-kde-along-unity

**Comment by andyx1975** [comment]
you can use your ubuntu installation... just enter the following commands:

sudo apt-get update
sudo apt-get install kubuntu-desktop

Then reboot ubuntu and choose the kde desktop on the login screen.

Here are also some tutorials to do this:
https://www.youtube.com/results?search_query=ubuntu+install+kde+desktop

**Comment by branflake2267** [comment]
Sure enough it does it on mine. These are system tabs so I think this is an upstream issue. 
![screen shot 2016-01-09 at 10 17 59 am](https://cloud.githubusercontent.com/assets/1326504/12217598/50d6b1a6-b6ba-11e5-95c2-4932e6f55d74.png)

**Comment by branflake2267** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476823 - here's the bug

**Comment by branflake2267** [comment]
I'm going to close the issue because it's upstream. If you find it's not after reading the eclipse bug let me know.

**Comment by andyx1975** [comment]
yeah ok thank you very much... seems to be the oxygen theme for gtk 3.0... so I downloaded this theme
http://www.deviantart.com/download/281431756/orion___gtk3_theme_by_satya164-d4nk24s.zip?token=81d78fe04a796ea80d3baaff272caae428c142f9&ts=1452534313

and extracted it and moved it with  "sudo mv ~/Downloads/Orion/ /usr/share/themes/". After moving the theme I can choose this as my gtk3 theme. Then everything is working fine with mars and linux mint 17.3. 

Thanks
Andy
